# Generated by Django 3.0.8 on 2020-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Harbor', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('isKorean', models.BooleanField()),
                ('Full_10', models.IntegerField()),
                ('Empty_10', models.IntegerField()),
                ('Full_20', models.IntegerField()),
                ('Empty_20', models.IntegerField()),
                ('Full_40', models.IntegerField()),
                ('Empty_40', models.IntegerField()),
                ('Full_other', models.IntegerField()),
                ('Empty_other', models.IntegerField()),
                ('Volume', models.IntegerField()),
            ],
        ),
    ]
