# Generated by Django 3.0.8 on 2020-07-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0002_containerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
