# Generated by Django 3.0.8 on 2020-07-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0004_auto_20200724_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='remember_me',
            field=models.NullBooleanField(),
        ),
    ]
